[package]
distribution = "2201.1.1"
name="tictactoe"
org="tedneward"
version="1.0.0"

[build-options]
observabilityIncluded = true
cloud = "docker"

[[platform.java11.dependency]]
groupId = "com.h2database"
artifactId = "h2"
version = "2.1.214"
